CREATE TABLE users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    user VARCHAR(25) NOT NULL,
    password (255) NOT NULL,
    photo VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)